#160 automated import
codegouvfr/sill pull request #176
Opened 2024-11-15 13:48 UTC by guillermau

2024-11-15 15:42 UTC, JeromeBu requested changes

2024-11-15 15:42 UTC, JeromeBu commented on api/src/core/adapters/hal/getHalSoftware.ts
> +    }
tu peux faire ton throw dans le catch directement.

```suggestion
    const res = await fetch(url).catch((error) => {
            console.error(error);
            throw new HalFetchError(undefined);
    });
```

2024-11-15 15:42 UTC, JeromeBu commented on api/src/core/adapters/hal/halRawSoftware.ts
> +        console.error('HalRawSoftwareToSoftwareForm', error);
là tu casses le système de type à cause du `let bibliographicReferences = undefined;`, la variable devient de type `any`.

je comprends pas l'interet de ce try catch. Tu étouffes l'erreur (catch + log, mais pas de throw) , et tu te retrouve à devoir gérer le cas undefined. Pour moi il vaux mieux laisser crasher. Ca simplifie toute la suite du code, qui n'a plus besoin de gérer ce cas undefined.

2024-11-15 15:42 UTC, JeromeBu commented on api/src/core/adapters/hal/halRawSoftware.ts
> +    fr_abstract_s?: string[]; // 235 / 1398
ça veut dire quoi ces chiffres ? 

2024-11-15 15:42 UTC, JeromeBu commented on api/src/core/adapters/hal/halRawSoftware.ts
> +    const license = bibliographicReferences && bibliographicReferences.license ?bibliographicReferences.license.join(", ") : undefined;
même remarque ici, je ne comprends pas ce try catch. Je veux bien qu'on en discute

2024-11-15 15:42 UTC, JeromeBu commented on api/src/core/usecases/feedDB.ts
> +}
comme discuté tout à l'heure :
tu peux récupérer tous les software en db d'une seule requête avec `dbApi.software.getAll()`. Ce qui évite 800 requêtes SQL.

Autres remarques 
- il faut pas typer la fonction `any`, ca ruine le sytème de typage.
- et niveau style : `return Promise.reslove(soft.id)`, pas utile car tu es dans une fonction async `return soft.id`, c'est suffisant, et implicitement une promise car la function est async.

Bonus : 
-  ajouter une methode dans le repo pour faire l'insertion groupée

```suggestion
export const feedDBfromHAL = (dbApi : DbApiV2)  => {
    return async () => {
        const softwares = await HAL.software.getAll();
        const softwaresInDb = await dbApi.software.getAll();

        return softwares.map(async software => {
            const newSoft = HalRawSoftwareToSoftwareForm(software);
            const soft = softwaresInDb.find(({id}) => newSoft.id === id);
            if (soft) return soft.id
          
            console.log('Importing HAL : ', software.docid);
            return dbApi.software.create({ formData: newSoft, externalDataOrigin: 'HAL', agentId: undefined });
            }
        });        
    }
}
```

2024-11-15 15:42 UTC, JeromeBu commented on api/src/core/usecases/readWriteSillData/types.ts
> +    similarSoftwareExternalDataIds: string[]; //
tu as besoins de ces commentaires ? 

2024-11-15 15:42 UTC, JeromeBu commented on api/src/env.ts
> +    "feedFromSource": z.boolean(),
qu'est que tu penses de renommer : `initializeSoftwaresFromSource` ?

2024-11-15 15:42 UTC, JeromeBu commented on api/src/env.ts
> +        "feedFromSource": process.env.FEEDFROMSOURCE ? process.env.FEEDFROMSOURCE.toLowerCase() == "true" : false,
tu as une syntax plus courte :
```suggestion
        "feedFromSource": process.env.INITIALIZE_SOFTWARES_FROM_SOURCE?.toLowerCase() === 'true';
```

2024-11-19 09:03 UTC, guillermau commented
@JeromeBu tu as une idée de pourquoi la CI plante ? En local, le typecheck passe.

2024-11-19 13:43 UTC, JeromeBu commented
> @JeromeBu tu as une idée de pourquoi la CI plante ? En local, le typecheck passe.

La CI ne joue pas que les tests, ca joue le formatage, lint, compilation typescript et les test. Tu peux jouer la même chose que la CI en local avec :

```sh
yarn fullcheck
```

2024-11-20 10:09 UTC, guillermau commented on api/src/core/usecases/feedDB.ts
> +}
Pour le bonus, ça se fait en quelques secondes étant donné la quantité. Et ce n'est pas une fonction qu'on appellera souvent. Donc, je priorise sur autre chose.

2024-11-22 08:54 UTC, JeromeBu requested changes

2024-11-22 08:54 UTC, JeromeBu commented on api/.env.sh
> +  "botAgentEmail": $BOTAGENTEMAIL,
```suggestion
  "initializeSoftwareFromSource": $INIT_SOFT_FROM_SOURCE,
  "botAgentEmail": $BOT_AGENT_EMAIL,
```

2024-11-22 08:54 UTC, JeromeBu commented on api/src/core/bootstrap.ts
> +            const HAL = importFromHALSource(dbApi);
```suggestion
            const hal = importFromHALSource(dbApi);
```

2024-11-22 08:54 UTC, JeromeBu commented on api/src/core/usecases/importFromSource.ts
> +            : await dbApi.agent.add({ email: agentEmail, "isPublic": false, organization: "", about: undefined });
```suggestion
            : await dbApi.agent.add({ email: agentEmail, "isPublic": false, organization: "", about: "This is an automaticaly created user. For automations only." });
```

2024-11-22 08:54 UTC, JeromeBu commented on api/src/core/usecases/importFromSource.ts
> +import HAL from "../adapters/hal";
```suggestion
import { halGateway } from "../adapters/hal";
```

2024-11-22 08:54 UTC, JeromeBu commented on api/src/core/usecases/importFromSource.ts
> +        const softwareDb = await dbApi.software.getAll();
```suggestion
        const dbSoftwares = await dbApi.software.getAll();
```

2024-11-22 08:54 UTC, JeromeBu commented on api/src/core/usecases/importFromSource.ts
> +            const newSoft = HalRawSoftwareToSoftwareForm(software);
```suggestion
            const newSoft = halRawSoftwareToSoftwareForm(software);
```

2024-11-22 08:54 UTC, JeromeBu commented on api/src/core/usecases/readWriteSillData/types.ts
>      softwareId: number;
`id` as to map to `softwareId`

2024-11-22 08:54 UTC, JeromeBu commented on api/src/env.ts
>      };
même renomage que premier commentaire

2024-11-22 08:54 UTC, JeromeBu commented on deployments/docker-compose-example/.env.sample
> +BOTAGENTEMAIL=contact@sill.codegouv.fr
idem

2024-11-22 12:32 UTC, JeromeBu approved these changes

2024-11-22 12:35 UTC, merged