#125 generate good link for authors
codegouvfr/sill pull request #208
Opened 2024-12-03 10:39 UTC by guillermau

about #125 : Get author info and identify id provider
Resolve #168 : fix licence crash while importing and remove dependencies

2024-12-04 15:27 UTC, JeromeBu requested changes

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/adapters/dbApi/kysely/createPgSoftwareRepository.ts
>                          userAndReferentCountByOrganization: {},
stocker systématiquement, devUrl en DB

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/adapters/dbApi/kysely/kysely.database.ts
> +            url?: string;
```suggestion
            url: string;
```

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/adapters/hal/getHalSoftwareExternalData.ts
> +                return Object.assign({ "url": `https://orcid.org/${id}` }, base);
```suggestion
                return {
                   ...base,
                   url: "..."
                }
```

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/adapters/hal/getHalSoftwareExternalData.ts
> +                return Object.assign({ "url": `https://hal.science/search/index/q/*/authIdHal_s/${id}` }, base);
idem

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/adapters/hal/getHalSoftwareExternalData.ts
> +            );
idem

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/ports/GetSoftwareExternalData.ts
> +        url?: string;
obligatoire

2024-12-04 15:27 UTC, JeromeBu commented on api/src/core/usecases/importFromSource.ts
>                  console.log("Importing HAL : ", software.docid);
log à virer peut-être ? Ou s'il est là pour rester `console.info`

2024-12-04 15:27 UTC, JeromeBu commented on api/src/types/codemeta.ts
> +    applicationCategory: string[]; // TODO
enlever les commentaires

2024-12-11 09:50 UTC, JeromeBu commented on api/src/core/adapters/hal/getHalSoftwareExternalData.ts
> +            license: codemetaSoftware?.license?.[0] ?? "undefined",
"undefined" en string ?

2024-12-11 13:07 UTC, guillermau commented on api/src/core/adapters/hal/getHalSoftwareExternalData.ts
> +            license: codemetaSoftware?.license?.[0] ?? "undefined",
Oui c'est une très bonne remarque. Je crois que j'aimerai presque rejeté le soft car il n'y a pas de licence avec un throw error mais cela fera planté en boucle.

J'ai demandé que faire de ce cas à l'équipe.

2024-12-11 13:16 UTC, guillermau commented on api/src/core/adapters/hal/getHalSoftwareExternalData.ts
> +            license: codemetaSoftware?.license?.[0] ?? "undefined",
J'ai ouvert #232 pour le follow up.

2024-12-11 13:43 UTC, merged